# Vizualisation of data INMET
source: [INMET :: BDMEP](https://bdmep.inmet.gov.br/) 
  
- *weather data*
- *whole country datasets*

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
current_dir = Path(Path.cwd()).parent.parent
data_dir = current_dir / "data"
source_data_dir = data_dir / "source"
print(data_dir)

d:\pedro\Programacao\.Projetos\dengue_prediction\dengue_prediction\data

In [3]:

import re
import unicodedata
 
def show_columns(df, n_range = 7):
    df = list(df.columns)
    l = []
    range = n_range
    for c in df:
        if range == n_range:
            print(l)
            l = []
            range = 0
        range += 1
        l.append(c)
    print("\n")

def normalize_column(col):
    # tira acentos
    col = unicodedata.normalize("NFKD", col).encode("ascii", "ignore").decode("utf-8")
    # minúsculas
    col = col.lower()
    # troca qualquer coisa que não seja letra ou número por _
    col = re.sub(r"[^a-z0-9]+", "_", col)
    # remove _ no começo e no fim
    col = col.strip("_")
    return col

In [4]:
def prep_show(df):
    # remove coluns with more than 40% missing values
    df = df.loc[
        :, df.isnull().mean() < 0.4
    ]
    df.columns = [normalize_column(col) for col in df.columns]

    show_columns(df=df)
    print(f"porcentagem de valores ausentes:\n{(df.isnull().mean() * 100).sort_values(ascending=False)}%")
    return df

In [5]:
weather_dir = source_data_dir / "weather_data"
path = weather_dir / "INMET_NE_PE_A301_RECIFE_01-01-2013_A_31-12-2013.csv"
weather_2013 = pd.read_csv(path, sep=";", encoding="latin1", skiprows=8, decimal=",")

In [6]:
weather_dir = source_data_dir / "weather_data"

year = 2013
path = weather_dir / f"INMET_NE_PE_A301_RECIFE_01-01-{year}_A_31-12-{year}.csv"
df_2013 = pd.read_csv(path, sep=";", encoding="latin1", skiprows=8, decimal=",")
df_2013 = prep_show(df_2013)
df_2013.head()

[]
['data_yyyy_mm_dd', 'hora_utc', 'precipitacao_total_horario_mm', 'pressao_atmosferica_ao_nivel_da_estacao_horaria_mb', 'pressao_atmosferica_max_na_hora_ant_aut_mb', 'pressao_atmosferica_min_na_hora_ant_aut_mb', 'radiacao_global_kj_m2']
['temperatura_do_ar_bulbo_seco_horaria_c', 'temperatura_do_ponto_de_orvalho_c', 'temperatura_maxima_na_hora_ant_aut_c', 'temperatura_minima_na_hora_ant_aut_c', 'temperatura_orvalho_max_na_hora_ant_aut_c', 'temperatura_orvalho_min_na_hora_ant_aut_c', 'umidade_rel_max_na_hora_ant_aut']


porcentagem de valores ausentes:
data_yyyy_mm_dd                                       0.0
hora_utc                                              0.0
precipitacao_total_horario_mm                         0.0
pressao_atmosferica_ao_nivel_da_estacao_horaria_mb    0.0
pressao_atmosferica_max_na_hora_ant_aut_mb            0.0
pressao_atmosferica_min_na_hora_ant_aut_mb            0.0
radiacao_global_kj_m2                                 0.0
temperatura_do_ar_bulbo_seco_horaria_c                0.0
temperatura_do_ponto_de_orvalho_c                     0.0
temperatura_maxima_na_hora_ant_aut_c                  0.0
temperatura_minima_na_hora_ant_aut_c                  0.0
temperatura_orvalho_max_na_hora_ant_aut_c             0.0
temperatura_orvalho_min_na_hora_ant_aut_c             0.0
umidade_rel_max_na_hora_ant_aut                       0.0
umidade_rel_min_na_hora_ant_aut                       0.0
umidade_relativa_do_ar_horaria                        0.0
vento_direcao_horaria_gr_gr                           0.0
vento_rajada_maxima_m_s                               0.0
vento_velocidade_horaria_m_s                          0.0
dtype: float64%

,data_yyyy_mm_dd,hora_utc,precipitacao_total_horario_mm,pressao_atmosferica_ao_nivel_da_estacao_horaria_mb,pressao_atmosferica_max_na_hora_ant_aut_mb,pressao_atmosferica_min_na_hora_ant_aut_mb,radiacao_global_kj_m2,temperatura_do_ar_bulbo_seco_horaria_c,temperatura_do_ponto_de_orvalho_c,temperatura_maxima_na_hora_ant_aut_c,temperatura_minima_na_hora_ant_aut_c,temperatura_orvalho_max_na_hora_ant_aut_c,temperatura_orvalho_min_na_hora_ant_aut_c,umidade_rel_max_na_hora_ant_aut,umidade_rel_min_na_hora_ant_aut,umidade_relativa_do_ar_horaria,vento_direcao_horaria_gr_gr,vento_rajada_maxima_m_s,vento_velocidade_horaria_m_s
0,2013-01-01,00:00,0.0,1012.4,1012.4,1012.1,-9999.0,26.5,22.1,26.7,26.5,22.2,21.2,77,72,77,155,4.5,1.6
1,2013-01-01,01:00,0.0,1012.4,1012.5,1012.3,-9999.0,26.4,20.9,26.7,26.4,22.1,20.7,77,70,72,156,4.7,1.5
2,2013-01-01,02:00,0.0,1012.1,1012.5,1012.1,-9999.0,26.3,21.9,26.5,26.3,21.9,21.0,76,72,76,158,4.7,1.8
3,2013-01-01,03:00,0.6,1011.5,1012.1,1011.5,-9999.0,25.1,22.5,26.4,24.8,22.6,21.9,86,76,86,120,5.3,2.0
4,2013-01-01,04:00,0.0,1010.9,1011.5,1010.9,-9999.0,25.4,22.0,25.6,25.0,22.5,21.9,86,81,82,118,4.5,1.5

In [7]:
weather_dir = source_data_dir / "weather_data"

year = 2014
path = weather_dir / f"INMET_NE_PE_A301_RECIFE_01-01-{year}_A_31-12-{year}.csv"
df_2014 = pd.read_csv(path, sep=";", encoding="latin1", skiprows=8, decimal=",")
df_2014 = prep_show(df_2014)
df_2014.head()

[]
['data_yyyy_mm_dd', 'hora_utc', 'precipitacao_total_horario_mm', 'pressao_atmosferica_ao_nivel_da_estacao_horaria_mb', 'pressao_atmosferica_max_na_hora_ant_aut_mb', 'pressao_atmosferica_min_na_hora_ant_aut_mb', 'radiacao_global_kj_m2']
['temperatura_do_ar_bulbo_seco_horaria_c', 'temperatura_do_ponto_de_orvalho_c', 'temperatura_maxima_na_hora_ant_aut_c', 'temperatura_minima_na_hora_ant_aut_c', 'temperatura_orvalho_max_na_hora_ant_aut_c', 'temperatura_orvalho_min_na_hora_ant_aut_c', 'umidade_rel_max_na_hora_ant_aut']


porcentagem de valores ausentes:
data_yyyy_mm_dd                                       0.0
hora_utc                                              0.0
precipitacao_total_horario_mm                         0.0
pressao_atmosferica_ao_nivel_da_estacao_horaria_mb    0.0
pressao_atmosferica_max_na_hora_ant_aut_mb            0.0
pressao_atmosferica_min_na_hora_ant_aut_mb            0.0
radiacao_global_kj_m2                                 0.0
temperatura_do_ar_bulbo_seco_horaria_c                0.0
temperatura_do_ponto_de_orvalho_c                     0.0
temperatura_maxima_na_hora_ant_aut_c                  0.0
temperatura_minima_na_hora_ant_aut_c                  0.0
temperatura_orvalho_max_na_hora_ant_aut_c             0.0
temperatura_orvalho_min_na_hora_ant_aut_c             0.0
umidade_rel_max_na_hora_ant_aut                       0.0
umidade_rel_min_na_hora_ant_aut                       0.0
umidade_relativa_do_ar_horaria                        0.0
vento_direcao_horaria_gr_gr                           0.0
vento_rajada_maxima_m_s                               0.0
vento_velocidade_horaria_m_s                          0.0
dtype: float64%

,data_yyyy_mm_dd,hora_utc,precipitacao_total_horario_mm,pressao_atmosferica_ao_nivel_da_estacao_horaria_mb,pressao_atmosferica_max_na_hora_ant_aut_mb,pressao_atmosferica_min_na_hora_ant_aut_mb,radiacao_global_kj_m2,temperatura_do_ar_bulbo_seco_horaria_c,temperatura_do_ponto_de_orvalho_c,temperatura_maxima_na_hora_ant_aut_c,temperatura_minima_na_hora_ant_aut_c,temperatura_orvalho_max_na_hora_ant_aut_c,temperatura_orvalho_min_na_hora_ant_aut_c,umidade_rel_max_na_hora_ant_aut,umidade_rel_min_na_hora_ant_aut,umidade_relativa_do_ar_horaria,vento_direcao_horaria_gr_gr,vento_rajada_maxima_m_s,vento_velocidade_horaria_m_s
0,2014-01-01,00:00,0.0,1012.7,1012.8,1012.4,-9999.0,26.3,20.5,26.5,26.2,20.5,19.7,71,67,70,107,5.5,1.3
1,2014-01-01,01:00,0.0,1012.7,1012.8,1012.6,-9999.0,26.2,20.6,26.3,25.9,20.6,19.9,72,69,71,112,4.5,1.7
2,2014-01-01,02:00,0.0,1012.4,1012.7,1012.4,-9999.0,25.9,20.4,26.2,25.7,20.6,19.9,72,69,72,109,5.1,1.4
3,2014-01-01,03:00,0.0,1011.5,1012.4,1011.5,-9999.0,25.7,20.1,26.1,25.5,20.5,20.0,73,70,71,111,4.5,1.7
4,2014-01-01,04:00,0.0,1011.0,1011.5,1010.9,-9999.0,25.8,20.6,25.9,25.2,20.7,20.0,75,71,73,113,5.3,2.1

In [8]:
weather_dir = source_data_dir / "weather_data"

year = 2019
path = weather_dir / f"INMET_NE_PE_A301_RECIFE_01-01-{year}_A_31-12-{year}.csv"
df_2019 = pd.read_csv(path, sep=";", encoding="latin1", skiprows=8, decimal=",")
df_2019 = prep_show(df_2019)
df_2019.head()

[]
['data', 'hora_utc', 'precipitacao_total_horario_mm', 'pressao_atmosferica_ao_nivel_da_estacao_horaria_mb', 'pressao_atmosferica_max_na_hora_ant_aut_mb', 'pressao_atmosferica_min_na_hora_ant_aut_mb', 'temperatura_do_ar_bulbo_seco_horaria_c']
['temperatura_do_ponto_de_orvalho_c', 'temperatura_maxima_na_hora_ant_aut_c', 'temperatura_minima_na_hora_ant_aut_c', 'temperatura_orvalho_max_na_hora_ant_aut_c', 'temperatura_orvalho_min_na_hora_ant_aut_c', 'umidade_rel_max_na_hora_ant_aut', 'umidade_rel_min_na_hora_ant_aut']


porcentagem de valores ausentes:
pressao_atmosferica_max_na_hora_ant_aut_mb            0.079909
pressao_atmosferica_min_na_hora_ant_aut_mb            0.079909
umidade_rel_min_na_hora_ant_aut                       0.079909
temperatura_orvalho_min_na_hora_ant_aut_c             0.079909
temperatura_orvalho_max_na_hora_ant_aut_c             0.079909
temperatura_minima_na_hora_ant_aut_c                  0.079909
temperatura_maxima_na_hora_ant_aut_c                  0.079909
umidade_rel_max_na_hora_ant_aut                       0.079909
precipitacao_total_horario_mm                         0.057078
temperatura_do_ar_bulbo_seco_horaria_c                0.057078
pressao_atmosferica_ao_nivel_da_estacao_horaria_mb    0.057078
temperatura_do_ponto_de_orvalho_c                     0.057078
umidade_relativa_do_ar_horaria                        0.057078
data                                                  0.000000
hora_utc                                              0.000000
dtype: float64%

,data,hora_utc,precipitacao_total_horario_mm,pressao_atmosferica_ao_nivel_da_estacao_horaria_mb,pressao_atmosferica_max_na_hora_ant_aut_mb,pressao_atmosferica_min_na_hora_ant_aut_mb,temperatura_do_ar_bulbo_seco_horaria_c,temperatura_do_ponto_de_orvalho_c,temperatura_maxima_na_hora_ant_aut_c,temperatura_minima_na_hora_ant_aut_c,temperatura_orvalho_max_na_hora_ant_aut_c,temperatura_orvalho_min_na_hora_ant_aut_c,umidade_rel_max_na_hora_ant_aut,umidade_rel_min_na_hora_ant_aut,umidade_relativa_do_ar_horaria
0,2019/01/01,0000 UTC,0.0,1013.0,1013.0,1012.8,27.0,22.2,27.1,26.9,22.4,22.1,76.0,75.0,75.0
1,2019/01/01,0100 UTC,0.0,1012.8,1013.0,1012.8,26.7,22.0,27.1,26.6,22.2,21.9,76.0,74.0,76.0
2,2019/01/01,0200 UTC,0.0,1012.5,1012.8,1012.5,26.6,22.1,26.8,26.5,22.2,21.9,76.0,76.0,76.0
3,2019/01/01,0300 UTC,0.0,1011.8,1012.5,1011.8,26.3,22.0,26.7,26.3,22.2,22.0,78.0,76.0,77.0
4,2019/01/01,0400 UTC,0.0,1011.4,1011.8,1011.4,26.1,21.8,26.6,26.1,22.2,21.7,77.0,76.0,77.0